name: meme
version: "0.9"
summary: meme
description: |
  A package manager for the memepool.

grade: stable

apps:
  meme:
    command: $SNAP/meme

parts:
  meme:
    override-build: ./autogen.sh
    plugin: autotools
    build-packages:
      - asciidoc
      - automake
      - autopoint
      - autotools-dev
      - curl
      - docbook
      - docbook-xsl
      - docbook-to-man
      - fakeroot
      - gcc
      - gettext
      - gnupg
      - make
      - libarchive13
      - libarchive-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - libxslt1.1
      - libxslt1-dev
      - m4
      - pkgconf
      - pkg-config
      - libtool
      - wget
      - xsltproc
    stage-packages:
      - libc6
