name: meme
version: "0.9"
summary: meme
description: |
  A package manager for the memepool.

confinement: devmode

apps:
  meme:
    command: meme

parts:
  meme:
    plugin: autotools
    build-packages:
      - asciidoc
      - autopoint
      - curl
      - docbook
      - docbook-xsl
      - fakeroot
      - gcc
      - gettext
      - gnupg
      - make
      - libarchive13
      - libarchive-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - libxslt1.1
      - libxslt1-dev
      - pkg-config
      - libtool
      - wget
